/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjerciciosClaseUT1;

import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author penga
 */
public class Encuesta extends javax.swing.JFrame implements Runnable {

    Thread thread;
    boolean empezarPago = false;

    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        edadLabel = new javax.swing.JLabel();
        profesionTextField = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        edadComboBox = new javax.swing.JComboBox<>();
        profesionLabel = new javax.swing.JLabel();
        numHermanosSpinner = new javax.swing.JSpinner();
        numHermanosLabel = new javax.swing.JLabel();
        sexoRadioButton1 = new javax.swing.JRadioButton();
        sexoRadioButton2 = new javax.swing.JRadioButton();
        deporteCheckBox = new javax.swing.JCheckBox();
        deporteScrollPane = new javax.swing.JScrollPane();
        deportesList = new javax.swing.JList<>();
        contadorLabel = new javax.swing.JLabel();
        aficcionLabel = new javax.swing.JLabel();
        gradoCineLabel = new javax.swing.JLabel();
        gradoComprasLabel = new javax.swing.JLabel();
        gradoTvLabel = new javax.swing.JLabel();
        cineSlider = new javax.swing.JSlider();
        comprasSlider = new javax.swing.JSlider();
        televisionSlider = new javax.swing.JSlider();
        empezarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        deporteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator.setBackground(new java.awt.Color(204, 204, 204));
        separator.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 580, 10));

        edadLabel.setFont(edadLabel.getFont().deriveFont(edadLabel.getFont().getSize()+6f));
        edadLabel.setForeground(new java.awt.Color(0, 0, 0));
        edadLabel.setText("Edad: ");
        mainPanel.add(edadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, -1));

        profesionTextField.setFont(profesionTextField.getFont().deriveFont(profesionTextField.getFont().getSize()+6f));
        profesionTextField.setEnabled(false);
        profesionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionTextFieldActionPerformed(evt);
            }
        });
        mainPanel.add(profesionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        sexoLabel.setFont(sexoLabel.getFont().deriveFont(sexoLabel.getFont().getSize()+6f));
        sexoLabel.setForeground(new java.awt.Color(0, 0, 0));
        sexoLabel.setText("Sexo: ");
        mainPanel.add(sexoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        edadComboBox.setFont(edadComboBox.getFont().deriveFont(edadComboBox.getFont().getSize()+6f));
        edadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 0 y 18 años", "Entre 18 y 30 años", "Entre 30 y 64 años" }));
        edadComboBox.setEnabled(false);
        mainPanel.add(edadComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 210, -1));

        profesionLabel.setFont(profesionLabel.getFont().deriveFont(profesionLabel.getFont().getSize()+6f));
        profesionLabel.setForeground(new java.awt.Color(0, 0, 0));
        profesionLabel.setText("Profesión: ");
        mainPanel.add(profesionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        numHermanosSpinner.setFont(numHermanosSpinner.getFont().deriveFont(numHermanosSpinner.getFont().getSize()+6f));
        numHermanosSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        numHermanosSpinner.setEnabled(false);
        mainPanel.add(numHermanosSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, -1));

        numHermanosLabel.setFont(numHermanosLabel.getFont().deriveFont(numHermanosLabel.getFont().getSize()+6f));
        numHermanosLabel.setForeground(new java.awt.Color(0, 0, 0));
        numHermanosLabel.setText("Nº Hermanos: ");
        mainPanel.add(numHermanosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        sexoButtonGroup.add(sexoRadioButton1);
        sexoRadioButton1.setFont(sexoRadioButton1.getFont().deriveFont(sexoRadioButton1.getFont().getSize()+6f));
        sexoRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        sexoRadioButton1.setText("MUJER");
        sexoRadioButton1.setEnabled(false);
        sexoRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoRadioButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(sexoRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        sexoButtonGroup.add(sexoRadioButton2);
        sexoRadioButton2.setFont(sexoRadioButton2.getFont().deriveFont(sexoRadioButton2.getFont().getSize()+6f));
        sexoRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        sexoRadioButton2.setText("HOMBRE");
        sexoRadioButton2.setEnabled(false);
        mainPanel.add(sexoRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        deporteCheckBox.setFont(deporteCheckBox.getFont().deriveFont(deporteCheckBox.getFont().getSize()+6f));
        deporteCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        deporteCheckBox.setText("¿Practica algún deporte?");
        deporteCheckBox.setEnabled(false);
        deporteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deporteCheckBoxActionPerformed(evt);
            }
        });
        mainPanel.add(deporteCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        deporteScrollPane.setEnabled(false);

        deportesList.setFont(deportesList.getFont().deriveFont(deportesList.getFont().getSize()+6f));
        deportesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fútbol", "Tenis", "Tenis de mesa", "Baloncesto", "Balonmano", "Volleyball" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        deportesList.setEnabled(false);
        deporteScrollPane.setViewportView(deportesList);

        mainPanel.add(deporteScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 170, 90));

        contadorLabel.setFont(contadorLabel.getFont().deriveFont(contadorLabel.getFont().getSize()+6f));
        contadorLabel.setForeground(new java.awt.Color(255, 0, 51));
        mainPanel.add(contadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 170, 40));

        aficcionLabel.setFont(aficcionLabel.getFont().deriveFont(aficcionLabel.getFont().getSize()+6f));
        aficcionLabel.setForeground(new java.awt.Color(0, 0, 0));
        aficcionLabel.setText("Marque de 1 a 10 su grado de aficción a: ");
        mainPanel.add(aficcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        gradoCineLabel.setFont(gradoCineLabel.getFont().deriveFont(gradoCineLabel.getFont().getSize()+6f));
        gradoCineLabel.setForeground(new java.awt.Color(0, 0, 0));
        gradoCineLabel.setText("Ir al cine: ");
        mainPanel.add(gradoCineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        gradoComprasLabel.setFont(gradoComprasLabel.getFont().deriveFont(gradoComprasLabel.getFont().getSize()+6f));
        gradoComprasLabel.setForeground(new java.awt.Color(0, 0, 0));
        gradoComprasLabel.setText("Compras: ");
        mainPanel.add(gradoComprasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        gradoTvLabel.setFont(gradoTvLabel.getFont().deriveFont(gradoTvLabel.getFont().getSize()+6f));
        gradoTvLabel.setForeground(new java.awt.Color(0, 0, 0));
        gradoTvLabel.setText("Ver la televisión: ");
        mainPanel.add(gradoTvLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        cineSlider.setFont(cineSlider.getFont().deriveFont(cineSlider.getFont().getSize()+6f));
        cineSlider.setForeground(new java.awt.Color(0, 0, 0));
        cineSlider.setMajorTickSpacing(1);
        cineSlider.setMaximum(10);
        cineSlider.setMinorTickSpacing(1);
        cineSlider.setPaintLabels(true);
        cineSlider.setValue(5);
        cineSlider.setEnabled(false);
        mainPanel.add(cineSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        comprasSlider.setFont(comprasSlider.getFont().deriveFont(comprasSlider.getFont().getSize()+6f));
        comprasSlider.setForeground(new java.awt.Color(0, 0, 0));
        comprasSlider.setMajorTickSpacing(1);
        comprasSlider.setMaximum(10);
        comprasSlider.setMinorTickSpacing(1);
        comprasSlider.setPaintLabels(true);
        comprasSlider.setValue(5);
        comprasSlider.setEnabled(false);
        mainPanel.add(comprasSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        televisionSlider.setFont(televisionSlider.getFont().deriveFont(televisionSlider.getFont().getSize()+6f));
        televisionSlider.setForeground(new java.awt.Color(0, 0, 0));
        televisionSlider.setMajorTickSpacing(1);
        televisionSlider.setMaximum(10);
        televisionSlider.setMinorTickSpacing(1);
        televisionSlider.setPaintLabels(true);
        televisionSlider.setValue(5);
        televisionSlider.setEnabled(false);
        mainPanel.add(televisionSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        empezarButton.setFont(empezarButton.getFont().deriveFont(empezarButton.getFont().getSize()+6f));
        empezarButton.setForeground(new java.awt.Color(0, 0, 0));
        empezarButton.setText("EMPEZAR");
        empezarButton.setToolTipText("Empezará la encuesta y un contador");
        empezarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empezarButtonMouseClicked(evt);
            }
        });
        empezarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarButtonActionPerformed(evt);
            }
        });
        mainPanel.add(empezarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, 40));

        cancelarButton.setFont(cancelarButton.getFont().deriveFont(cancelarButton.getFont().getSize()+6f));
        cancelarButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarButton.setText("CANCELAR");
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseClicked(evt);
            }
        });
        mainPanel.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 130, 40));

        aceptarButton.setFont(aceptarButton.getFont().deriveFont(aceptarButton.getFont().getSize()+6f));
        aceptarButton.setForeground(new java.awt.Color(0, 0, 0));
        aceptarButton.setText("ACEPTAR");
        aceptarButton.setEnabled(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        mainPanel.add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 130, 40));

        deporteLabel.setFont(deporteLabel.getFont().deriveFont(deporteLabel.getFont().getSize()+6f));
        deporteLabel.setForeground(new java.awt.Color(0, 0, 0));
        deporteLabel.setText("¿Cúal?");
        mainPanel.add(deporteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profesionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionTextFieldActionPerformed

    private void sexoRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoRadioButton1ActionPerformed

    private void deporteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deporteCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deporteCheckBoxActionPerformed

    private void empezarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void empezarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarButtonMouseClicked

        disableComponents();

        if (empezarPago) {
            CreditCardDialog creditCardDialog = new CreditCardDialog(this, true);

            if (creditCardDialog.confirmClicked) {
                thread = new Thread(this);
                thread.start();
            }
            
        } else {
            thread = new Thread(this);
            thread.start();
        }

    }//GEN-LAST:event_empezarButtonMouseClicked

    public void disableComponents() {
        // TODO add your handling code here:
        
        aceptarButton.setEnabled(true);
        cineSlider.setEnabled(true);
        comprasSlider.setEnabled(true);
        deporteCheckBox.setEnabled(true);
        deporteScrollPane.setEnabled(true);
        deportesList.setEnabled(true);
        edadComboBox.setEnabled(true);
        empezarButton.setEnabled(false);
        numHermanosSpinner.setEnabled(true);
        profesionTextField.setEnabled(true);
        sexoRadioButton1.setEnabled(true);
        sexoRadioButton2.setEnabled(true);
        televisionSlider.setEnabled(true);
    }

    private void cancelarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MenuEncuesta();
    }//GEN-LAST:event_cancelarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JLabel aficcionLabel;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JSlider cineSlider;
    private javax.swing.JSlider comprasSlider;
    private javax.swing.JLabel contadorLabel;
    private javax.swing.JCheckBox deporteCheckBox;
    private javax.swing.JLabel deporteLabel;
    private javax.swing.JScrollPane deporteScrollPane;
    private javax.swing.JList<String> deportesList;
    private javax.swing.JComboBox<String> edadComboBox;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JButton empezarButton;
    private javax.swing.JLabel gradoCineLabel;
    private javax.swing.JLabel gradoComprasLabel;
    private javax.swing.JLabel gradoTvLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numHermanosLabel;
    private javax.swing.JSpinner numHermanosSpinner;
    private javax.swing.JLabel profesionLabel;
    private javax.swing.JTextField profesionTextField;
    private javax.swing.JSeparator separator;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JRadioButton sexoRadioButton1;
    private javax.swing.JRadioButton sexoRadioButton2;
    private javax.swing.JSlider televisionSlider;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        for (int j = 1; j >= 0; j--) {
            contadorLabel.setText("02:00s restantes");
            for (int i = 99; i >= 0; i--) {
                if (i < 10) {
                    contadorLabel.setText("0" + j + ":0" + i + "s restantes");
                } else {
                    contadorLabel.setText("0" + j + ":" + i + "s restantes");
                }

                try {
                    thread.sleep(9);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Encuesta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        aceptarButton.setEnabled(false);
        cineSlider.setEnabled(false);
        comprasSlider.setEnabled(false);
        deporteCheckBox.setEnabled(false);
        deporteScrollPane.setEnabled(false);
        deportesList.setEnabled(false);
        edadComboBox.setEnabled(false);
        empezarButton.setEnabled(true);
        numHermanosSpinner.setEnabled(false);
        profesionTextField.setEnabled(false);
        sexoRadioButton1.setEnabled(false);
        sexoRadioButton2.setEnabled(false);
        televisionSlider.setEnabled(false);

        empezarButton.setText("5€ para otros 2seg");
        empezarPago = true;
    }
    
    public void changeFontSize(int fontSize) {
         List<Component> components= getAllComponents(this);
        for(Component comp: components){
            if (comp instanceof JLabel || comp instanceof JTextField) {
                 comp.setFont(new Font(comp.getFont().getFontName(),0,fontSize));
            }
        }
       SwingUtilities.updateComponentTreeUI(this);
    }
    
    public List<Component> getAllComponents(final Container c) {
    Component[] comps = c.getComponents();
    List<Component> compList = new ArrayList<>();
    for (Component comp : comps) {
        compList.add(comp);
        if (comp instanceof Container)
            compList.addAll(getAllComponents((Container) comp));
    }
    return compList;
}
}
