/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjerciciosClaseUT1;

import java.awt.Desktop;
import java.awt.Font;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author penga
 */
public class MenuEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form MenuEncuesta
     */
    public MenuEncuesta() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        encuestaButton = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuEncuesta = new javax.swing.JMenu();
        menuItemEncuesta = new javax.swing.JMenuItem();
        menuAccesibilidad = new javax.swing.JMenu();
        cambiarTemas = new javax.swing.JMenuItem();
        cambiarTamano = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        encuestaButton.setBackground(new java.awt.Color(255, 255, 255));
        encuestaButton.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        encuestaButton.setForeground(new java.awt.Color(255, 0, 51));
        encuestaButton.setText("HACER ENCUESTA AQUÍ");
        encuestaButton.setBorder(null);
        encuestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encuestaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encuestaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encuestaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        menuEncuesta.setText("Encuesta");

        menuItemEncuesta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemEncuesta.setText("Hacer Encuesta");
        menuItemEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEncuestaActionPerformed(evt);
            }
        });
        menuEncuesta.add(menuItemEncuesta);

        menu.add(menuEncuesta);

        menuAccesibilidad.setText("Accesibilidad");
        menuAccesibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccesibilidadActionPerformed(evt);
            }
        });

        cambiarTemas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cambiarTemas.setText("Cambiar Temas");
        cambiarTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTemasActionPerformed(evt);
            }
        });
        menuAccesibilidad.add(cambiarTemas);

        cambiarTamano.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cambiarTamano.setText("Cambiar Tamaño");
        cambiarTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTamanoActionPerformed(evt);
            }
        });
        menuAccesibilidad.add(cambiarTamano);

        menu.add(menuAccesibilidad);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEncuestaActionPerformed
        // TODO add your handling code here:
        Encuesta encuesta = new Encuesta();
        encuesta.updateUI();
        this.dispose();
    }//GEN-LAST:event_menuItemEncuestaActionPerformed

    private void encuestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encuestaButtonActionPerformed
        // TODO add your handling code here:

        Encuesta encuesta = new Encuesta();
        encuesta.updateUI();
        this.dispose();
    }//GEN-LAST:event_encuestaButtonActionPerformed

    private void menuAccesibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccesibilidadActionPerformed
        // TODO add your handling code here:

         
    }//GEN-LAST:event_menuAccesibilidadActionPerformed

    private void cambiarTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTemasActionPerformed
        // TODO add your handling code here:
        new CambiarTema(this, false,this);
        this.dispose();
    }//GEN-LAST:event_cambiarTemasActionPerformed

    private void cambiarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTamanoActionPerformed
        // TODO add your handling code here:
         new CambiarTamaño(this, false,this);
         this.dispose();
    }//GEN-LAST:event_cambiarTamanoActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEncuesta().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cambiarTamano;
    private javax.swing.JMenuItem cambiarTemas;
    private javax.swing.JButton encuestaButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAccesibilidad;
    private javax.swing.JMenu menuEncuesta;
    private javax.swing.JMenuItem menuItemEncuesta;
    // End of variables declaration//GEN-END:variables

   public void changeFontSize(int fontSize) {
        UIManager.getLookAndFeelDefaults().put("defaultFont", new Font("Segoe UI", Font.PLAIN, fontSize));
        updateUI();
    }
    
    public void updateUI() {
       SwingUtilities.updateComponentTreeUI(this);
    }
}
