/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjerciciosClaseUT1;

import java.awt.Color;

/**
 *
 * @author penga
 */
public class tabbedPane extends javax.swing.JFrame {

    private int x;
    private int y;
    
    /**
     * Creates new form TabbedPane
     */
    public tabbedPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        sidePanel3 = new javax.swing.JPanel();
        messagePaneLabel = new javax.swing.JLabel();
        sidePanel1 = new javax.swing.JPanel();
        colorChooserLabel = new javax.swing.JLabel();
        sidePanel2 = new javax.swing.JPanel();
        fileChooserLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        tabbedPane1 = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        tabbedPane2 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        tabbedPane3 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(101, 174, 244));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel3.setBackground(new java.awt.Color(101, 174, 244));

        messagePaneLabel.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        messagePaneLabel.setForeground(new java.awt.Color(255, 255, 255));
        messagePaneLabel.setText("Message Panel");
        messagePaneLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagePaneLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                messagePaneLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                messagePaneLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidePanel3Layout = new javax.swing.GroupLayout(sidePanel3);
        sidePanel3.setLayout(sidePanel3Layout);
        sidePanel3Layout.setHorizontalGroup(
            sidePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel3Layout.createSequentialGroup()
                .addComponent(messagePaneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanel3Layout.setVerticalGroup(
            sidePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messagePaneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        sidePanel.add(sidePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        sidePanel1.setBackground(new java.awt.Color(101, 174, 244));

        colorChooserLabel.setBackground(new java.awt.Color(101, 174, 244));
        colorChooserLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        colorChooserLabel.setForeground(new java.awt.Color(255, 255, 255));
        colorChooserLabel.setText("Color Chooser");
        colorChooserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorChooserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorChooserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colorChooserLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidePanel1Layout = new javax.swing.GroupLayout(sidePanel1);
        sidePanel1.setLayout(sidePanel1Layout);
        sidePanel1Layout.setHorizontalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorChooserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        sidePanel1Layout.setVerticalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorChooserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        sidePanel.add(sidePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        sidePanel2.setBackground(new java.awt.Color(101, 174, 244));

        fileChooserLabel.setBackground(new java.awt.Color(101, 174, 244));
        fileChooserLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        fileChooserLabel.setForeground(new java.awt.Color(255, 255, 255));
        fileChooserLabel.setText("File Chooser");
        fileChooserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileChooserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileChooserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fileChooserLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidePanel2Layout = new javax.swing.GroupLayout(sidePanel2);
        sidePanel2.setLayout(sidePanel2Layout);
        sidePanel2Layout.setHorizontalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        sidePanel2Layout.setVerticalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        sidePanel.add(sidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 450));

        topPanel.setBackground(new java.awt.Color(41, 92, 187));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 730, 70));

        javax.swing.GroupLayout tabbedPane1Layout = new javax.swing.GroupLayout(tabbedPane1);
        tabbedPane1.setLayout(tabbedPane1Layout);
        tabbedPane1Layout.setHorizontalGroup(
            tabbedPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        tabbedPane1Layout.setVerticalGroup(
            tabbedPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        tabbedPane.addTab("colorTab", tabbedPane1);

        javax.swing.GroupLayout tabbedPane2Layout = new javax.swing.GroupLayout(tabbedPane2);
        tabbedPane2.setLayout(tabbedPane2Layout);
        tabbedPane2Layout.setHorizontalGroup(
            tabbedPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedPane2Layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabbedPane2Layout.setVerticalGroup(
            tabbedPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        tabbedPane.addTab("fileTab", tabbedPane2);

        javax.swing.GroupLayout tabbedPane3Layout = new javax.swing.GroupLayout(tabbedPane3);
        tabbedPane3.setLayout(tabbedPane3Layout);
        tabbedPane3Layout.setHorizontalGroup(
            tabbedPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        tabbedPane3Layout.setVerticalGroup(
            tabbedPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        tabbedPane.addTab("messageTab", tabbedPane3);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 730, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorChooserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorChooserLabelMouseEntered
        // TODO add your handling code here:
        sidePanel1.setBackground(new Color(41,92,187));
        
    }//GEN-LAST:event_colorChooserLabelMouseEntered

    private void colorChooserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorChooserLabelMouseExited
        // TODO add your handling code here:
        sidePanel1.setBackground(new Color(101,174,244));
    }//GEN-LAST:event_colorChooserLabelMouseExited

    private void fileChooserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileChooserLabelMouseEntered
        // TODO add your handling code here:
         sidePanel2.setBackground(new Color(41,92,187));
    }//GEN-LAST:event_fileChooserLabelMouseEntered

    private void fileChooserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileChooserLabelMouseExited
        // TODO add your handling code here:
         sidePanel2.setBackground(new Color(101,174,244));
    }//GEN-LAST:event_fileChooserLabelMouseExited

    private void messagePaneLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneLabelMouseEntered
        // TODO add your handling code here:
         sidePanel3.setBackground(new Color(41,92,187));
    }//GEN-LAST:event_messagePaneLabelMouseEntered

    private void messagePaneLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneLabelMouseExited
        // TODO add your handling code here:
        sidePanel3.setBackground(new Color(101,174,244));
    }//GEN-LAST:event_messagePaneLabelMouseExited

    private void colorChooserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorChooserLabelMouseClicked
        // TODO add your handling code here:
        tabbedPane.setSelectedComponent(tabbedPane1);
       
    }//GEN-LAST:event_colorChooserLabelMouseClicked

    private void fileChooserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileChooserLabelMouseClicked
        // TODO add your handling code here:
        tabbedPane.setSelectedComponent(tabbedPane2);
    }//GEN-LAST:event_fileChooserLabelMouseClicked

    private void messagePaneLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneLabelMouseClicked
        // TODO add your handling code here:
        tabbedPane.setSelectedComponent(tabbedPane3);
    }//GEN-LAST:event_messagePaneLabelMouseClicked

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        // TODO add your handling code here:
        int xOnScreen = evt.getXOnScreen();
        int yOnScreen = evt.getYOnScreen();
        
        this.setLocation( xOnScreen- x, yOnScreen-y);
    }//GEN-LAST:event_topPanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabbedPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorChooserLabel;
    private javax.swing.JLabel fileChooserLabel;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel messagePaneLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanel1;
    private javax.swing.JPanel sidePanel2;
    private javax.swing.JPanel sidePanel3;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel tabbedPane1;
    private javax.swing.JPanel tabbedPane2;
    private javax.swing.JPanel tabbedPane3;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
