/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaBeanComponent;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *  Clase utilizado como editor de propiedades (al darle a los 3 puntitos para editar, mostrará este panel)
 *  Tendremos que controlar sus eventos, y hacer un Getter de la clase que contiene las propiedades
 *  a modificar (en este caso, BackgroundImage) -> Ver más abajo.
 * @author xZ3NER
 */
public class ImagePropertiesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagePropertiesPanel
     */
    public ImagePropertiesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        imagePathTextF = new javax.swing.JTextField();
        opacityLabel = new javax.swing.JLabel();
        opacitySlider = new javax.swing.JSlider();

        imageLabel.setText("Image:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        imagePathTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePathTextFActionPerformed(evt);
            }
        });

        opacityLabel.setText("Opacity:");

        opacitySlider.setMajorTickSpacing(10);
        opacitySlider.setPaintLabels(true);
        opacitySlider.setPaintTicks(true);
        opacitySlider.setSnapToTicks(true);
        opacitySlider.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opacityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opacitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagePathTextF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLabel)
                    .addComponent(submitButton)
                    .addComponent(imagePathTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opacityLabel)
                    .addComponent(opacitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imagePathTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePathTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagePathTextFActionPerformed

    /*
    *   Para cargar una imagen del sistema y mostrar su ruta absoluta, en un text field.
    */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        
        int resul = jFileChooser.showOpenDialog(this);
        
        if (resul == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            imagePathTextF.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /*
    *   Método Getter de una nueva instacia de nuestra clase que contiene las propiedades a modificar
    *   Obtendremos los datos introducidos por el usuario, y devolveremos el objeto con los datos cargados.
    */
    public BackgroundImage getBackgroundImage() {
            File imageFile = new File(imagePathTextF.getText());
            Float opacity = opacitySlider.getValue()/100f;
            
            return new BackgroundImage(imageFile, opacity);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagePathTextF;
    private javax.swing.JLabel opacityLabel;
    private javax.swing.JSlider opacitySlider;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
