/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1y2;

/**
 *
 * @author penga
 */
public class Encuesta extends javax.swing.JFrame {

    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        edadLabel = new javax.swing.JLabel();
        profesionTextField = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        edadComboBox = new javax.swing.JComboBox<>();
        profesionLabel = new javax.swing.JLabel();
        numHermanosSpinner = new javax.swing.JSpinner();
        numHermanosLabel = new javax.swing.JLabel();
        sexoRadioButton1 = new javax.swing.JRadioButton();
        sexoRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 493));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator.setBackground(new java.awt.Color(204, 204, 204));
        separator.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 580, 10));

        edadLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        edadLabel.setForeground(new java.awt.Color(0, 0, 0));
        edadLabel.setText("Edad: ");
        mainPanel.add(edadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 50, -1));

        profesionTextField.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        profesionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionTextFieldActionPerformed(evt);
            }
        });
        mainPanel.add(profesionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 25, 130, -1));

        sexoLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(0, 0, 0));
        sexoLabel.setText("Sexo: ");
        mainPanel.add(sexoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        edadComboBox.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        edadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 0 y 18 años", "Entre 18 y 30 años", "Entre 30 y 64 años" }));
        mainPanel.add(edadComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 25, 210, -1));

        profesionLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        profesionLabel.setForeground(new java.awt.Color(0, 0, 0));
        profesionLabel.setText("Profesión: ");
        mainPanel.add(profesionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        numHermanosSpinner.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        numHermanosSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        mainPanel.add(numHermanosSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 65, 70, -1));

        numHermanosLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        numHermanosLabel.setForeground(new java.awt.Color(0, 0, 0));
        numHermanosLabel.setText("Nº Hermanos: ");
        mainPanel.add(numHermanosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        sexoButtonGroup.add(sexoRadioButton1);
        sexoRadioButton1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        sexoRadioButton1.setText("MUJER");
        sexoRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoRadioButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(sexoRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        sexoButtonGroup.add(sexoRadioButton2);
        sexoRadioButton2.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        sexoRadioButton2.setText("HOMBRE");
        mainPanel.add(sexoRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        mainPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profesionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionTextFieldActionPerformed

    private void sexoRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> edadComboBox;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numHermanosLabel;
    private javax.swing.JSpinner numHermanosSpinner;
    private javax.swing.JLabel profesionLabel;
    private javax.swing.JTextField profesionTextField;
    private javax.swing.JSeparator separator;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JRadioButton sexoRadioButton1;
    private javax.swing.JRadioButton sexoRadioButton2;
    // End of variables declaration//GEN-END:variables
}
