/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ExamenJavaBean;

/**
 *
 * @author xZ3NER
 */
public class DigitalClockProperties extends javax.swing.JPanel {

    /**
     * Creates new form DigitalClockProperties
     */
    public DigitalClockProperties() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        longFormatCheckB = new javax.swing.JCheckBox();

        longFormatCheckB.setText("24h clock format");
        longFormatCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longFormatCheckBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(longFormatCheckB)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(longFormatCheckB)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void longFormatCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longFormatCheckBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_longFormatCheckBActionPerformed

    public Clock getClock() {
        boolean longFormat = longFormatCheckB.isSelected();
        return new Clock(longFormat);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox longFormatCheckB;
    // End of variables declaration//GEN-END:variables
}
