/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UT1;

/**
 *
 * @author penga
 */
public class ReservaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReservaDialog
     */
    public ReservaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoCocinaButtonG = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        separator2 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        contactoLabel = new javax.swing.JLabel();
        nombreTextF = new javax.swing.JTextField();
        contactoTextF = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        numJornadaSpinner = new javax.swing.JSpinner();
        fechaLabel = new javax.swing.JLabel();
        numAsistentesLabel = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        numAsistentesSpinner = new javax.swing.JSpinner();
        tipoLabel = new javax.swing.JLabel();
        bufeRadioB = new javax.swing.JRadioButton();
        tipoCocinaLabel = new javax.swing.JLabel();
        noPrecisaRadioB = new javax.swing.JRadioButton();
        cartaRadioB = new javax.swing.JRadioButton();
        citaChefRadioB = new javax.swing.JRadioButton();
        numJornadasLabel = new javax.swing.JLabel();
        fechaSpinner = new javax.swing.JSpinner();
        habitacionesCheckB = new javax.swing.JCheckBox();
        habitacionesLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        confirmarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(212, 192, 251));
        mainPanel.setForeground(new java.awt.Color(109, 0, 220));

        separator2.setForeground(new java.awt.Color(109, 0, 220));

        titleLabel.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(193, 2, 238));
        titleLabel.setText("Reservas Salón Habana");

        contactoLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        contactoLabel.setForeground(new java.awt.Color(207, 82, 241));
        contactoLabel.setText("Teléfono de contacto: ");

        nombreTextF.setBackground(new java.awt.Color(238, 136, 205));
        nombreTextF.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        nombreTextF.setForeground(new java.awt.Color(238, 2, 163));
        nombreTextF.setToolTipText("Nombre de la persona quien la reserva.");
        nombreTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFActionPerformed(evt);
            }
        });

        contactoTextF.setBackground(new java.awt.Color(238, 136, 205));
        contactoTextF.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        contactoTextF.setForeground(new java.awt.Color(238, 2, 163));
        contactoTextF.setToolTipText("Teléfono para contactar con el solicitante.");
        contactoTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoTextFActionPerformed(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(207, 82, 241));
        nombreLabel.setText("Nombre: ");

        numJornadaSpinner.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        numJornadaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numJornadaSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numJornadaSpinner.setEnabled(false);

        fechaLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(207, 82, 241));
        fechaLabel.setText("Fecha: ");

        numAsistentesLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        numAsistentesLabel.setForeground(new java.awt.Color(207, 82, 241));
        numAsistentesLabel.setText("<html>Número de <br>asistentes: </html>");

        tipoComboBox.setBackground(new java.awt.Color(238, 136, 205));
        tipoComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tipoComboBox.setForeground(new java.awt.Color(238, 2, 163));
        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        tipoComboBox.setToolTipText("Congreso habilitará opciones extras.");
        tipoComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoComboBoxItemStateChanged(evt);
            }
        });

        numAsistentesSpinner.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        numAsistentesSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        numAsistentesSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tipoLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(207, 82, 241));
        tipoLabel.setText("Tipo: ");

        tipoCocinaButtonG.add(bufeRadioB);
        bufeRadioB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        bufeRadioB.setForeground(new java.awt.Color(238, 2, 163));
        bufeRadioB.setText("Bufé");
        bufeRadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tipoCocinaLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        tipoCocinaLabel.setForeground(new java.awt.Color(207, 82, 241));
        tipoCocinaLabel.setText("Tipo de cocina: ");

        tipoCocinaButtonG.add(noPrecisaRadioB);
        noPrecisaRadioB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        noPrecisaRadioB.setForeground(new java.awt.Color(238, 2, 163));
        noPrecisaRadioB.setText("No precisa");
        noPrecisaRadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tipoCocinaButtonG.add(cartaRadioB);
        cartaRadioB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cartaRadioB.setForeground(new java.awt.Color(238, 2, 163));
        cartaRadioB.setText("Carta");
        cartaRadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tipoCocinaButtonG.add(citaChefRadioB);
        citaChefRadioB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        citaChefRadioB.setForeground(new java.awt.Color(238, 2, 163));
        citaChefRadioB.setText("Cita con un chef");
        citaChefRadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        numJornadasLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        numJornadasLabel.setForeground(new java.awt.Color(207, 82, 241));
        numJornadasLabel.setText("Número de jornadas: ");
        numJornadasLabel.setEnabled(false);

        fechaSpinner.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fechaSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1665737443175L), null, null, java.util.Calendar.DAY_OF_MONTH));
        fechaSpinner.setToolTipText("Fecha de la reserva.");

        habitacionesCheckB.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        habitacionesCheckB.setForeground(new java.awt.Color(238, 2, 163));
        habitacionesCheckB.setText("Habitaciones");
        habitacionesCheckB.setToolTipText("Facilita habitaciones para los asistentes.");
        habitacionesCheckB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habitacionesCheckB.setEnabled(false);

        habitacionesLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        habitacionesLabel.setForeground(new java.awt.Color(207, 82, 241));
        habitacionesLabel.setText("Se requiere para los asistentes: ");
        habitacionesLabel.setEnabled(false);

        separator1.setBackground(new java.awt.Color(109, 0, 220));
        separator1.setForeground(new java.awt.Color(109, 0, 220));

        confirmarButton.setBackground(new java.awt.Color(238, 136, 205));
        confirmarButton.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        confirmarButton.setForeground(new java.awt.Color(238, 2, 163));
        confirmarButton.setText("Confirmar");
        confirmarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numAsistentesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numAsistentesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipoCocinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cartaRadioB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(bufeRadioB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(noPrecisaRadioB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(citaChefRadioB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habitacionesLabel)
                            .addComponent(habitacionesCheckB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numJornadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numJornadaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(confirmarButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(440, 440, 440))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(nombreTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(contactoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(fechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numAsistentesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoLabel)
                            .addComponent(numJornadasLabel)
                            .addComponent(tipoCocinaLabel))
                        .addGap(5, 5, 5)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numJornadaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(habitacionesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(habitacionesCheckB))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bufeRadioB)
                                    .addComponent(fechaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaRadioB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(citaChefRadioB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noPrecisaRadioB)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAsistentesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactoTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoTextFActionPerformed

    private void nombreTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void tipoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoComboBoxItemStateChanged
        // TODO add your handling code here:
        if (tipoComboBox.getSelectedIndex() == 2) {
            numJornadasLabel.setEnabled(true);
            numJornadaSpinner.setEnabled(true);
            habitacionesLabel.setEnabled(true);
            habitacionesCheckB.setEnabled(true);
        }else{
             numJornadasLabel.setEnabled(false);
            numJornadaSpinner.setEnabled(false);
            habitacionesLabel.setEnabled(false);
            habitacionesCheckB.setEnabled(false);
        }
    }//GEN-LAST:event_tipoComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReservaDialog dialog = new ReservaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bufeRadioB;
    private javax.swing.JRadioButton cartaRadioB;
    private javax.swing.JRadioButton citaChefRadioB;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel contactoLabel;
    private javax.swing.JTextField contactoTextF;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JSpinner fechaSpinner;
    private javax.swing.JCheckBox habitacionesCheckB;
    private javax.swing.JLabel habitacionesLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton noPrecisaRadioB;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextF;
    private javax.swing.JLabel numAsistentesLabel;
    private javax.swing.JSpinner numAsistentesSpinner;
    private javax.swing.JSpinner numJornadaSpinner;
    private javax.swing.JLabel numJornadasLabel;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.ButtonGroup tipoCocinaButtonG;
    private javax.swing.JLabel tipoCocinaLabel;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
